"""Add timestamp fields

Revision ID: e83283b48cdd
Revises: 1efde32f058d
Create Date: 2025-03-03 12:18:26.990342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83283b48cdd'
down_revision: Union[str, None] = '1efde32f058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('tags', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
